#define FILES_BACK_COL       COL_BLACK

#define FILES_COL_NORMAL_B   COL_BLACK
#define FILES_COL_NORMAL_F   COL_WHITE
#define FILES_COL_PLAY_B     COL_RED_DARK
#define FILES_COL_PLAY_F     COL_RED_LIGHT
#define FILES_COL_DIR_B      COL_GREEN_DARK
#define FILES_COL_DIR_F      COL_GREEN_LIGHT
